# -*- coding: utf-8 -*-
from plot_area import PlotArea

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CompGeomApp(object):
    def setupUi(self, CompGeomApp):
        CompGeomApp.setObjectName("CompGeomApp")
        CompGeomApp.resize(683, 451)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(CompGeomApp)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_dot = QtWidgets.QPushButton(CompGeomApp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_dot.sizePolicy().hasHeightForWidth())
        self.pushButton_dot.setSizePolicy(sizePolicy)
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.horizontalLayout.addWidget(self.pushButton_dot)
        self.pushButton_bline = QtWidgets.QPushButton(CompGeomApp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_bline.sizePolicy().hasHeightForWidth())
        self.pushButton_bline.setSizePolicy(sizePolicy)
        self.pushButton_bline.setObjectName("pushButton_bline")
        self.horizontalLayout.addWidget(self.pushButton_bline)
        self.pushButton_poly = QtWidgets.QPushButton(CompGeomApp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_poly.sizePolicy().hasHeightForWidth())
        self.pushButton_poly.setSizePolicy(sizePolicy)
        self.pushButton_poly.setObjectName("pushButton_poly")
        self.horizontalLayout.addWidget(self.pushButton_poly)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.plot_widget = PlotArea(CompGeomApp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_widget.sizePolicy().hasHeightForWidth())
        self.plot_widget.setSizePolicy(sizePolicy)
        self.plot_widget.setObjectName("plot_widget")
        self.verticalLayout.addWidget(self.plot_widget)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.algo_list_widget = QtWidgets.QListWidget(CompGeomApp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.algo_list_widget.sizePolicy().hasHeightForWidth())
        self.algo_list_widget.setSizePolicy(sizePolicy)
        self.algo_list_widget.setObjectName("algo_list_widget")
        self.verticalLayout_2.addWidget(self.algo_list_widget)
        self.pushButton_run = QtWidgets.QPushButton(CompGeomApp)
        self.pushButton_run.setObjectName("pushButton_run")
        self.verticalLayout_2.addWidget(self.pushButton_run)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_exchange = QtWidgets.QPushButton(CompGeomApp)
        self.pushButton_exchange.setObjectName("pushButton_exchange")
        self.verticalLayout_3.addWidget(self.pushButton_exchange)
        self.pushButton_to_plot = QtWidgets.QPushButton(CompGeomApp)
        self.pushButton_to_plot.setObjectName("pushButton_to_plot")
        self.verticalLayout_3.addWidget(self.pushButton_to_plot)
        self.pushButton_to_text = QtWidgets.QPushButton(CompGeomApp)
        self.pushButton_to_text.setObjectName("pushButton_to_text")
        self.verticalLayout_3.addWidget(self.pushButton_to_text)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.text_widget = QtWidgets.QTextEdit(CompGeomApp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_widget.sizePolicy().hasHeightForWidth())
        self.text_widget.setSizePolicy(sizePolicy)
        self.text_widget.setObjectName("text_widget")
        self.horizontalLayout_2.addWidget(self.text_widget)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)

        self.retranslateUi(CompGeomApp)
        QtCore.QMetaObject.connectSlotsByName(CompGeomApp)

    def retranslateUi(self, CompGeomApp):
        _translate = QtCore.QCoreApplication.translate
        CompGeomApp.setWindowTitle(_translate("CompGeomApp", "CompGeomApp"))
        self.pushButton_dot.setText(_translate("CompGeomApp", "dot"))
        self.pushButton_bline.setText(_translate("CompGeomApp", "bline"))
        self.pushButton_poly.setText(_translate("CompGeomApp", "polygon"))
        self.pushButton_run.setText(_translate("CompGeomApp", "Run"))
        self.pushButton_exchange.setText(_translate("CompGeomApp", "<>"))
        self.pushButton_to_plot.setText(_translate("CompGeomApp", "<"))
        self.pushButton_to_text.setText(_translate("CompGeomApp", ">"))

